# Generated by Django 3.2.9 on 2021-11-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
